name: Flake8

on:
  push:
    branches-ignore:
      - "dependabot/**"
      - weblate
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements-lint.txt
      - name: Run flake8
        run: |
          echo "::add-matcher::.github/matchers/flake8.json"
          pre-commit run flake8 --all
          echo "::remove-matcher owner=flake8::"
